name: Continuos Integration

on: 
  pull_request:
    branches: 
      ['develop']

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4
      - name: Using Node.js
        uses: action/setup-node@v3
        with:
          node-version: 19.x
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run preview
